include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    include_file_not_found: ignore

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - unnecessary_this

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4